#!/usr/bin/env node
import readline from 'node:readline';
import { MockMortgageAdapter } from './adapters/mock.js';
import { SnapshotMortgageAdapter } from './adapters/snapshot.js';
import { toolDefinitions, callTool } from './tools.js';
const MODERN='2026-07-28'; const LEGACY=['2025-11-25','2025-06-18','2025-03-26','2024-11-05']; const SUPPORTED=[MODERN,...LEGACY];
const mode=process.env.UWM_MCP_MODE||'snapshot'; const adapter=mode==='mock'?new MockMortgageAdapter():new SnapshotMortgageAdapter(process.env.UWM_MCP_SNAPSHOT);
const serverInfo={name:'uwm-mortgage-mcp',version:'0.1.0-private.0',description:'Read-only mortgage tracking MCP server'};
const instructions='Read-only mortgage tracking. Never initiates payments, transfers, ACH, autopay enrollment, or other account mutations.';
function send(payload){process.stdout.write(`${JSON.stringify(payload)}\n`);} function ok(id,result){send({jsonrpc:'2.0',id,result});} function fail(id,code,message,data){send({jsonrpc:'2.0',id,error:{code,message,...(data?{data}:{})}});} function toolResult(value){return{content:[{type:'text',text:JSON.stringify(value,null,2)}],structuredContent:value,isError:false};} function toolError(error){return{content:[{type:'text',text:error instanceof Error?error.message:String(error)}],isError:true};} function capabilities(){return{tools:{listChanged:false}};}
function requestProtocol(msg){return msg?.params?._meta?.['io.modelcontextprotocol/protocolVersion']||msg?._meta?.['io.modelcontextprotocol/protocolVersion']||null;}
async function handle(msg){if(!msg||msg.jsonrpc!=='2.0')return;if(!('id'in msg))return;const{id,method,params={}}=msg;try{if(method==='server/discover')return ok(id,{resultType:'complete',supportedVersions:SUPPORTED,capabilities:capabilities(),serverInfo,instructions});if(method==='initialize'){const requested=params.protocolVersion;const selected=LEGACY.includes(requested)?requested:LEGACY[0];return ok(id,{protocolVersion:selected,capabilities:capabilities(),serverInfo,instructions});}const pv=requestProtocol(msg);if(pv&&!SUPPORTED.includes(pv))return fail(id,-32001,'Unsupported protocol version',{supportedVersions:SUPPORTED});if(method==='ping')return ok(id,{});if(method==='tools/list')return ok(id,{tools:toolDefinitions()});if(method==='tools/call'){try{return ok(id,toolResult(await callTool(adapter,params.name,params.arguments??{})));}catch(error){return ok(id,toolError(error));}}return fail(id,-32601,'Method not found');}catch(error){return fail(id,-32603,'Internal error',{message:error.message});}}
const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity}); rl.on('line',async(line)=>{if(!line.trim())return;try{await handle(JSON.parse(line));}catch(error){process.stderr.write(`uwm-mortgage-mcp: ${error.message}\n`);}});
